drop table if exists item_price_reductions CASCADE;
drop table if exists item_suppliers CASCADE;
drop table if exists items CASCADE;
drop table if exists price_reduction CASCADE;
drop table if exists roles CASCADE;
drop table if exists suppliers CASCADE;
drop table if exists users CASCADE;
drop table if exists users_roles CASCADE;

create table item_price_reductions (item_id bigint not null, price_reduction_id bigint not null);
create table item_suppliers (item_id bigint not null, supplier_id bigint not null);
create table items (id bigint generated by default as identity, creation_date date not null, description varchar(255) not null, item_code varchar(255) not null, price double not null, state varchar(255), user_id bigint not null, primary key (id));
create table price_reduction (id bigint generated by default as identity, end_date date not null, reduction_price double not null, start_date date not null, state varchar(255), primary key (id));
create table roles (id bigint generated by default as identity, rol varchar(30), primary key (id));
create table suppliers (id bigint generated by default as identity, country varchar(50) not null, name varchar(30) not null, primary key (id));
create table users (id bigint generated by default as identity, lastname varchar(20) not null, name varchar(20) not null, password varchar(100) not null, username varchar(20) not null, primary key (id));
create table users_roles (user_id bigint not null, role_id bigint not null);
alter table item_price_reductions add constraint UK7itq5x6j4f420subrc7tw4pcc unique (item_id, price_reduction_id);
alter table item_suppliers add constraint UKj9mdylj613npxut1ev9gqvc3q unique (item_id, supplier_id);
alter table items add constraint UK_n3wi2ihmiiviolnt3ifaxppsk unique (item_code);
alter table roles add constraint UK_g00thobnv3twutok8x6furkx1 unique (rol);
alter table suppliers add constraint UK_eegixpn11chp14nb25tl3ucv0 unique (name);
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint UKfqc3bu90y5m73gsaio7vosp0w unique (user_id, role_id);
alter table item_price_reductions add constraint FKiowixhf1owcp05opynd3ct5e9 foreign key (price_reduction_id) references price_reduction;
alter table item_price_reductions add constraint FK5fedmyrg4lrw0uy1yc03n4wqh foreign key (item_id) references items;
alter table item_suppliers add constraint FK8frqu3ul6ydp87gif6h9u1ehi foreign key (supplier_id) references suppliers;
alter table item_suppliers add constraint FKddtvte9qaebd1wfn6a05px2cv foreign key (item_id) references items;
alter table items add constraint FKft8pmhndq1kntvyfaqcybhxvx foreign key (user_id) references users;
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles;
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users;

INSERT INTO roles (ROL) VALUES ('USER');
INSERT INTO roles (ROL) VALUES ('ADMIN');

INSERT INTO users (NAME, LASTNAME, USERNAME, PASSWORD) VALUES('Francisco', 'Carrasco', 'Fran', '1234');
INSERT INTO users (NAME, LASTNAME, USERNAME, PASSWORD) VALUES('Antonia', 'Fernández', 'Antonia', '1234');
INSERT INTO users (NAME, LASTNAME, USERNAME, PASSWORD) VALUES('Antonia Del Carmen', 'Fernandez', 'Antonita', '1234');

INSERT INTO users_roles (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO users_roles (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO users_roles (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO users_roles (USER_ID, ROLE_ID) VALUES (3, 1);

INSERT INTO suppliers (NAME, COUNTRY) VALUES ('supplier1', 'German');
INSERT INTO suppliers (NAME, COUNTRY) VALUES ('supplier2', 'Spain');
INSERT INTO suppliers (NAME, COUNTRY) VALUES ('supplier3', 'Spain');
INSERT INTO suppliers (NAME, COUNTRY) VALUES ('supplier4', 'Spain');
INSERT INTO suppliers (NAME, COUNTRY) VALUES ('ferreteria S.L', 'France');

INSERT INTO price_reduction (REDUCTION_PRICE, START_DATE, END_DATE, STATE) VALUES (15.95, '2021-10-15', '2021-10-21', 'INACTIVE');
INSERT INTO price_reduction (REDUCTION_PRICE, START_DATE, END_DATE, STATE) VALUES (10.95, '2021-10-16', '2021-10-20', 'INACTIVE');
INSERT INTO price_reduction (REDUCTION_PRICE, START_DATE, END_DATE, STATE) VALUES (5.95, '2021-11-15', '2021-10-18', 'ACTIVE');

INSERT INTO items (ITEM_CODE, DESCRIPTION, PRICE, STATE, CREATION_DATE, USER_ID) VALUES ('asd213', 'Alta', 59.95, 'ACTIVE', '2021-10-22', 1);
INSERT INTO items (ITEM_CODE, DESCRIPTION, PRICE, STATE, CREATION_DATE, USER_ID) VALUES ('qwr456', 'Alta', 79.95, 'ACTIVE', '2021-10-22', 2);
INSERT INTO items (ITEM_CODE, DESCRIPTION, PRICE, STATE, CREATION_DATE, USER_ID) VALUES ('wxz750', 'Alta', 69.95, 'ACTIVE', '2021-10-22', 1);
INSERT INTO items (ITEM_CODE, DESCRIPTION, PRICE, STATE, CREATION_DATE, USER_ID) VALUES ('bnm987', 'Alta', 49.95, 'ACTIVE', '2021-10-22', 1);

INSERT INTO item_suppliers (ITEM_ID, SUPPLIER_ID) VALUES (1, 1);
INSERT INTO item_suppliers (ITEM_ID, SUPPLIER_ID) VALUES (1, 2);
INSERT INTO item_suppliers (ITEM_ID, SUPPLIER_ID) VALUES (1, 4);
INSERT INTO item_suppliers (ITEM_ID, SUPPLIER_ID) VALUES (2, 1);
INSERT INTO item_suppliers (ITEM_ID, SUPPLIER_ID) VALUES (2, 2);
INSERT INTO item_suppliers (ITEM_ID, SUPPLIER_ID) VALUES (3, 5);
INSERT INTO item_suppliers (ITEM_ID, SUPPLIER_ID) VALUES (4, 3);

INSERT INTO item_price_reductions (ITEM_ID, PRICE_REDUCTION_ID) VALUES (1, 1);
INSERT INTO item_price_reductions (ITEM_ID, PRICE_REDUCTION_ID) VALUES (1, 3);